# Generated by Django 4.2.3 on 2023-07-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=50)),
                ('work_created_at', models.TimeField()),
                ('work_updated_at', models.TimeField()),
                ('phone_number', models.IntegerField()),
                ('facebook_link', models.CharField(max_length=30)),
                ('twitter_link', models.CharField(max_length=30)),
                ('link1', models.CharField(max_length=30)),
                ('link2', models.CharField(max_length=30)),
                ('link3', models.CharField(max_length=30)),
            ],
        ),
    ]
