# Generated by Django 4.2.3 on 2023-07-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='link1',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='link2',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='link3',
        ),
        migrations.AddField(
            model_name='contact',
            name='instagram_link',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='linkedin_link',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='telegram_link',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='youtube_link',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='facebook_link',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='twitter_link',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='work_created_at',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='work_updated_at',
            field=models.TimeField(null=True),
        ),
    ]
