# Generated by Django 4.2.3 on 2023-07-07 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_contact_finish_work_contact_start_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address_en',
            field=models.CharField(max_length=50, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='contact',
            name='address_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='contact',
            name='address_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='contact',
            name='email_en',
            field=models.EmailField(max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='contact',
            name='email_ru',
            field=models.EmailField(max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='contact',
            name='email_uz',
            field=models.EmailField(max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='contact',
            name='facebook_link_en',
            field=models.CharField(max_length=30, null=True, verbose_name='facebook_link'),
        ),
        migrations.AddField(
            model_name='contact',
            name='facebook_link_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='facebook_link'),
        ),
        migrations.AddField(
            model_name='contact',
            name='facebook_link_uz',
            field=models.CharField(max_length=30, null=True, verbose_name='facebook_link'),
        ),
        migrations.AddField(
            model_name='contact',
            name='finish_work_en',
            field=models.CharField(max_length=10, null=True, verbose_name='finish_work'),
        ),
        migrations.AddField(
            model_name='contact',
            name='finish_work_ru',
            field=models.CharField(max_length=10, null=True, verbose_name='finish_work'),
        ),
        migrations.AddField(
            model_name='contact',
            name='finish_work_uz',
            field=models.CharField(max_length=10, null=True, verbose_name='finish_work'),
        ),
        migrations.AddField(
            model_name='contact',
            name='instagram_link_en',
            field=models.CharField(max_length=30, null=True, verbose_name='instagram_link'),
        ),
        migrations.AddField(
            model_name='contact',
            name='instagram_link_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='instagram_link'),
        ),
        migrations.AddField(
            model_name='contact',
            name='instagram_link_uz',
            field=models.CharField(max_length=30, null=True, verbose_name='instagram_link'),
        ),
        migrations.AddField(
            model_name='contact',
            name='linkedin_link_en',
            field=models.CharField(max_length=30, null=True, verbose_name='linkedin_link'),
        ),
        migrations.AddField(
            model_name='contact',
            name='linkedin_link_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='linkedin_link'),
        ),
        migrations.AddField(
            model_name='contact',
            name='linkedin_link_uz',
            field=models.CharField(max_length=30, null=True, verbose_name='linkedin_link'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_number_en',
            field=models.CharField(max_length=17, null=True, verbose_name='phone_number'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_number_ru',
            field=models.CharField(max_length=17, null=True, verbose_name='phone_number'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_number_uz',
            field=models.CharField(max_length=17, null=True, verbose_name='phone_number'),
        ),
        migrations.AddField(
            model_name='contact',
            name='start_work_en',
            field=models.CharField(max_length=10, null=True, verbose_name='start_work'),
        ),
        migrations.AddField(
            model_name='contact',
            name='start_work_ru',
            field=models.CharField(max_length=10, null=True, verbose_name='start_work'),
        ),
        migrations.AddField(
            model_name='contact',
            name='start_work_uz',
            field=models.CharField(max_length=10, null=True, verbose_name='start_work'),
        ),
        migrations.AddField(
            model_name='contact',
            name='telegram_link_en',
            field=models.CharField(max_length=30, null=True, verbose_name='telegram_link'),
        ),
        migrations.AddField(
            model_name='contact',
            name='telegram_link_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='telegram_link'),
        ),
        migrations.AddField(
            model_name='contact',
            name='telegram_link_uz',
            field=models.CharField(max_length=30, null=True, verbose_name='telegram_link'),
        ),
        migrations.AddField(
            model_name='contact',
            name='twitter_link_en',
            field=models.CharField(max_length=30, null=True, verbose_name='twitter_link'),
        ),
        migrations.AddField(
            model_name='contact',
            name='twitter_link_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='twitter_link'),
        ),
        migrations.AddField(
            model_name='contact',
            name='twitter_link_uz',
            field=models.CharField(max_length=30, null=True, verbose_name='twitter_link'),
        ),
        migrations.AddField(
            model_name='contact',
            name='work_created_at_en',
            field=models.TimeField(null=True, verbose_name='work_created_at'),
        ),
        migrations.AddField(
            model_name='contact',
            name='work_created_at_ru',
            field=models.TimeField(null=True, verbose_name='work_created_at'),
        ),
        migrations.AddField(
            model_name='contact',
            name='work_created_at_uz',
            field=models.TimeField(null=True, verbose_name='work_created_at'),
        ),
        migrations.AddField(
            model_name='contact',
            name='work_updated_at_en',
            field=models.TimeField(null=True, verbose_name='work_updated_at'),
        ),
        migrations.AddField(
            model_name='contact',
            name='work_updated_at_ru',
            field=models.TimeField(null=True, verbose_name='work_updated_at'),
        ),
        migrations.AddField(
            model_name='contact',
            name='work_updated_at_uz',
            field=models.TimeField(null=True, verbose_name='work_updated_at'),
        ),
        migrations.AddField(
            model_name='contact',
            name='youtube_link_en',
            field=models.CharField(max_length=30, null=True, verbose_name='youtube_link'),
        ),
        migrations.AddField(
            model_name='contact',
            name='youtube_link_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='youtube_link'),
        ),
        migrations.AddField(
            model_name='contact',
            name='youtube_link_uz',
            field=models.CharField(max_length=30, null=True, verbose_name='youtube_link'),
        ),
    ]
