# Generated by Django 4.2.3 on 2023-07-07 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_contact_address_en_contact_address_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='telegram_link',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='telegram_link_en',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='telegram_link_ru',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='telegram_link_uz',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='twitter_link',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='twitter_link_en',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='twitter_link_ru',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='twitter_link_uz',
        ),
    ]
