# Generated by Django 4.2.3 on 2023-07-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_steps_remove_contact_email_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=25)),
                ('title_en', models.CharField(max_length=25, null=True)),
                ('title_ru', models.CharField(max_length=25, null=True)),
                ('title_uz', models.CharField(max_length=25, null=True)),
                ('body', models.CharField(max_length=50)),
                ('body_en', models.CharField(max_length=50, null=True)),
                ('body_ru', models.CharField(max_length=50, null=True)),
                ('body_uz', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
