# Generated by Django 4.2.3 on 2023-07-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='icon',
            field=models.CharField(max_length=50),
        ),
    ]
