# Generated by Django 4.2.3 on 2023-07-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_card_title_alter_card_title_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='team_images')),
                ('title', models.CharField(max_length=30)),
                ('title_en', models.CharField(max_length=30, null=True)),
                ('title_ru', models.CharField(max_length=30, null=True)),
                ('title_uz', models.CharField(max_length=30, null=True)),
                ('work', models.CharField(max_length=30)),
                ('work_en', models.CharField(max_length=30, null=True)),
                ('work_ru', models.CharField(max_length=30, null=True)),
                ('work_uz', models.CharField(max_length=30, null=True)),
                ('position', models.CharField(max_length=30)),
                ('position_en', models.CharField(max_length=30, null=True)),
                ('position_ru', models.CharField(max_length=30, null=True)),
                ('position_uz', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
