# Generated by Django 4.2.3 on 2023-07-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='name')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='email')),
                ('subject', models.CharField(max_length=30, null=True, verbose_name='subject')),
                ('message', models.CharField(max_length=70, null=True, verbose_name='messages')),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='body',
            field=models.CharField(max_length=50, null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='card',
            name='body_en',
            field=models.CharField(max_length=50, null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='card',
            name='body_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='card',
            name='body_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='card',
            name='icon',
            field=models.CharField(max_length=50, null=True, verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='card',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='card',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='card',
            name='title_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='steps',
            name='body',
            field=models.CharField(max_length=100, null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='steps',
            name='body_en',
            field=models.CharField(max_length=100, null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='steps',
            name='body_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='steps',
            name='body_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='steps',
            name='title',
            field=models.CharField(max_length=30, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='steps',
            name='title_en',
            field=models.CharField(max_length=30, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='steps',
            name='title_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='steps',
            name='title_uz',
            field=models.CharField(max_length=30, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(null=True, upload_to='team_images', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='team',
            name='position',
            field=models.CharField(max_length=30, null=True, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='team',
            name='position_en',
            field=models.CharField(max_length=30, null=True, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='team',
            name='position_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='team',
            name='position_uz',
            field=models.CharField(max_length=30, null=True, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='team',
            name='title',
            field=models.CharField(max_length=30, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='team',
            name='title_en',
            field=models.CharField(max_length=30, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='team',
            name='title_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='team',
            name='title_uz',
            field=models.CharField(max_length=30, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='team',
            name='work',
            field=models.CharField(max_length=30, null=True, verbose_name='work'),
        ),
        migrations.AlterField(
            model_name='team',
            name='work_en',
            field=models.CharField(max_length=30, null=True, verbose_name='work'),
        ),
        migrations.AlterField(
            model_name='team',
            name='work_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='work'),
        ),
        migrations.AlterField(
            model_name='team',
            name='work_uz',
            field=models.CharField(max_length=30, null=True, verbose_name='work'),
        ),
    ]
