# Generated by Django 4.2.3 on 2023-07-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_callback_alter_card_body_alter_card_body_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callback',
            name='email_en',
            field=models.EmailField(max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='callback',
            name='email_ru',
            field=models.EmailField(max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='callback',
            name='email_uz',
            field=models.EmailField(max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='callback',
            name='message_en',
            field=models.CharField(max_length=70, null=True, verbose_name='messages'),
        ),
        migrations.AddField(
            model_name='callback',
            name='message_ru',
            field=models.CharField(max_length=70, null=True, verbose_name='messages'),
        ),
        migrations.AddField(
            model_name='callback',
            name='message_uz',
            field=models.CharField(max_length=70, null=True, verbose_name='messages'),
        ),
        migrations.AddField(
            model_name='callback',
            name='name_en',
            field=models.CharField(max_length=30, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='callback',
            name='name_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='callback',
            name='name_uz',
            field=models.CharField(max_length=30, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='callback',
            name='subject_en',
            field=models.CharField(max_length=30, null=True, verbose_name='subject'),
        ),
        migrations.AddField(
            model_name='callback',
            name='subject_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='subject'),
        ),
        migrations.AddField(
            model_name='callback',
            name='subject_uz',
            field=models.CharField(max_length=30, null=True, verbose_name='subject'),
        ),
    ]
