# Generated by Django 4.2.3 on 2023-07-07 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_callback_email_en_callback_email_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callback',
            name='email_en',
        ),
        migrations.RemoveField(
            model_name='callback',
            name='email_ru',
        ),
        migrations.RemoveField(
            model_name='callback',
            name='email_uz',
        ),
        migrations.RemoveField(
            model_name='callback',
            name='message_en',
        ),
        migrations.RemoveField(
            model_name='callback',
            name='message_ru',
        ),
        migrations.RemoveField(
            model_name='callback',
            name='message_uz',
        ),
        migrations.RemoveField(
            model_name='callback',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='callback',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='callback',
            name='name_uz',
        ),
        migrations.RemoveField(
            model_name='callback',
            name='subject_en',
        ),
        migrations.RemoveField(
            model_name='callback',
            name='subject_ru',
        ),
        migrations.RemoveField(
            model_name='callback',
            name='subject_uz',
        ),
    ]
