# Generated by Django 4.2.3 on 2023-07-07 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_callback_email_en_remove_callback_email_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=250, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=250, null=True, verbose_name='title')),
                ('title_uz', models.CharField(max_length=250, null=True, verbose_name='title')),
                ('summary', models.CharField(max_length=200, null=True, verbose_name='summary')),
                ('summary_en', models.CharField(max_length=200, null=True, verbose_name='summary')),
                ('summary_ru', models.CharField(max_length=200, null=True, verbose_name='summary')),
                ('summary_uz', models.CharField(max_length=200, null=True, verbose_name='summary')),
                ('body', models.CharField(max_length=300, null=True, verbose_name='body')),
                ('body_en', models.CharField(max_length=300, null=True, verbose_name='body')),
                ('body_ru', models.CharField(max_length=300, null=True, verbose_name='body')),
                ('body_uz', models.CharField(max_length=300, null=True, verbose_name='body')),
                ('author', models.CharField(max_length=70, null=True, verbose_name='author')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='photo')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=150, verbose_name='comment')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog', verbose_name='blog')),
            ],
        ),
    ]
