# Generated by Django 4.2.3 on 2023-07-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_blog_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='date',
        ),
        migrations.AddField(
            model_name='blog',
            name='day',
            field=models.CharField(help_text='E.x: 15 April 2023', max_length=50, null=True, verbose_name='day'),
        ),
        migrations.AddField(
            model_name='blog',
            name='day_en',
            field=models.CharField(help_text='E.x: 15 April 2023', max_length=50, null=True, verbose_name='day'),
        ),
        migrations.AddField(
            model_name='blog',
            name='day_ru',
            field=models.CharField(help_text='E.x: 15 April 2023', max_length=50, null=True, verbose_name='day'),
        ),
        migrations.AddField(
            model_name='blog',
            name='day_uz',
            field=models.CharField(help_text='E.x: 15 April 2023', max_length=50, null=True, verbose_name='day'),
        ),
    ]
