# Generated by Django 4.2.3 on 2023-07-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_blog_date_blog_day_blog_day_en_blog_day_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=models.CharField(max_length=900, null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='body_en',
            field=models.CharField(max_length=900, null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='body_ru',
            field=models.CharField(max_length=900, null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='body_uz',
            field=models.CharField(max_length=900, null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='summary',
            field=models.CharField(max_length=500, null=True, verbose_name='summary'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='summary_en',
            field=models.CharField(max_length=500, null=True, verbose_name='summary'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='summary_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='summary'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='summary_uz',
            field=models.CharField(max_length=500, null=True, verbose_name='summary'),
        ),
    ]
