# Generated by Django 4.2.3 on 2023-07-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_blog_options_alter_blog_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=50, null=True, verbose_name='icon')),
                ('title', models.CharField(max_length=250, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=250, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=250, null=True, verbose_name='title')),
                ('title_uz', models.CharField(max_length=250, null=True, verbose_name='title')),
                ('summary', models.CharField(max_length=500, null=True, verbose_name='summary')),
                ('summary_en', models.CharField(max_length=500, null=True, verbose_name='summary')),
                ('summary_ru', models.CharField(max_length=500, null=True, verbose_name='summary')),
                ('summary_uz', models.CharField(max_length=500, null=True, verbose_name='summary')),
                ('body', models.CharField(max_length=900, null=True, verbose_name='body')),
                ('body_en', models.CharField(max_length=900, null=True, verbose_name='body')),
                ('body_ru', models.CharField(max_length=900, null=True, verbose_name='body')),
                ('body_uz', models.CharField(max_length=900, null=True, verbose_name='body')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='photo')),
            ],
        ),
    ]
