# Generated by Django 4.2.3 on 2023-07-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='summary',
            field=models.TextField(null=True, verbose_name='summary'),
        ),
        migrations.AlterField(
            model_name='services',
            name='summary_en',
            field=models.TextField(null=True, verbose_name='summary'),
        ),
        migrations.AlterField(
            model_name='services',
            name='summary_ru',
            field=models.TextField(null=True, verbose_name='summary'),
        ),
        migrations.AlterField(
            model_name='services',
            name='summary_uz',
            field=models.TextField(null=True, verbose_name='summary'),
        ),
    ]
