# Generated by Django 4.2.3 on 2023-07-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_services_summary_alter_services_summary_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='team_images', verbose_name='image')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=30, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=30, null=True, verbose_name='name')),
                ('name_uz', models.CharField(max_length=30, null=True, verbose_name='name')),
                ('job', models.CharField(max_length=50, null=True, verbose_name='job')),
                ('job_en', models.CharField(max_length=50, null=True, verbose_name='job')),
                ('job_ru', models.CharField(max_length=50, null=True, verbose_name='job')),
                ('job_uz', models.CharField(max_length=50, null=True, verbose_name='job')),
                ('facebook_link', models.CharField(max_length=30, null=True, verbose_name='facebook_link')),
                ('instagram_link', models.CharField(max_length=30, null=True, verbose_name='instagram_link')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='email')),
            ],
        ),
    ]
