# Generated by Django 4.2.3 on 2023-07-10 09:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_ourteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='body_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='body_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='body_uz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='day',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='day'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='day_en',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='day'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='day_ru',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='day'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='day_uz',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='day'),
        ),
    ]
