# Generated by Django 4.2.3 on 2023-07-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_blog_updated_at_alter_blog_body_alter_blog_body_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=250, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=250, null=True, verbose_name='title')),
                ('title_uz', models.CharField(max_length=250, null=True, verbose_name='title')),
                ('body', models.TextField(null=True, verbose_name='body')),
                ('body_en', models.TextField(null=True, verbose_name='body')),
                ('body_ru', models.TextField(null=True, verbose_name='body')),
                ('body_uz', models.TextField(null=True, verbose_name='body')),
                ('consultants', models.IntegerField(null=True, verbose_name='consultants')),
                ('awards', models.IntegerField(null=True, verbose_name='awards')),
                ('cases', models.IntegerField(null=True, verbose_name='cases')),
                ('our_mission', models.CharField(max_length=255, null=True, verbose_name='our_mission')),
                ('our_mission_en', models.CharField(max_length=255, null=True, verbose_name='our_mission')),
                ('our_mission_ru', models.CharField(max_length=255, null=True, verbose_name='our_mission')),
                ('our_mission_uz', models.CharField(max_length=255, null=True, verbose_name='our_mission')),
                ('our_vision', models.CharField(max_length=255, null=True, verbose_name='our_vision')),
                ('our_vision_en', models.CharField(max_length=255, null=True, verbose_name='our_vision')),
                ('our_vision_ru', models.CharField(max_length=255, null=True, verbose_name='our_vision')),
                ('our_vision_uz', models.CharField(max_length=255, null=True, verbose_name='our_vision')),
            ],
        ),
        migrations.CreateModel(
            name='Faqs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(null=True, verbose_name='question')),
                ('question_en', models.TextField(null=True, verbose_name='question')),
                ('question_ru', models.TextField(null=True, verbose_name='question')),
                ('question_uz', models.TextField(null=True, verbose_name='question')),
                ('answer', models.TextField(null=True, verbose_name='answer')),
                ('answer_en', models.TextField(null=True, verbose_name='answer')),
                ('answer_ru', models.TextField(null=True, verbose_name='answer')),
                ('answer_uz', models.TextField(null=True, verbose_name='answer')),
            ],
        ),
        migrations.CreateModel(
            name='Our_keys_of_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=250, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=250, null=True, verbose_name='title')),
                ('title_uz', models.CharField(max_length=250, null=True, verbose_name='title')),
                ('body', models.TextField(null=True, verbose_name='body')),
                ('body_en', models.TextField(null=True, verbose_name='body')),
                ('body_ru', models.TextField(null=True, verbose_name='body')),
                ('body_uz', models.TextField(null=True, verbose_name='body')),
                ('benifits', models.TextField(null=True, verbose_name='benifits')),
                ('benifits_en', models.TextField(null=True, verbose_name='benifits')),
                ('benifits_ru', models.TextField(null=True, verbose_name='benifits')),
                ('benifits_uz', models.TextField(null=True, verbose_name='benifits')),
                ('mutual_funds', models.TextField(null=True, verbose_name='mutual_funds')),
                ('mutual_funds_en', models.TextField(null=True, verbose_name='mutual_funds')),
                ('mutual_funds_ru', models.TextField(null=True, verbose_name='mutual_funds')),
                ('mutual_funds_uz', models.TextField(null=True, verbose_name='mutual_funds')),
                ('company_growth', models.TextField(null=True, verbose_name='company_growth')),
                ('company_growth_en', models.TextField(null=True, verbose_name='company_growth')),
                ('company_growth_ru', models.TextField(null=True, verbose_name='company_growth')),
                ('company_growth_uz', models.TextField(null=True, verbose_name='company_growth')),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='body',
            field=models.TextField(max_length=50, null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='card',
            name='body_en',
            field=models.TextField(max_length=50, null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='card',
            name='body_ru',
            field=models.TextField(max_length=50, null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='card',
            name='body_uz',
            field=models.TextField(max_length=50, null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='services',
            name='body',
            field=models.TextField(null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='services',
            name='body_en',
            field=models.TextField(null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='services',
            name='body_ru',
            field=models.TextField(null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='services',
            name='body_uz',
            field=models.TextField(null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='steps',
            name='body',
            field=models.TextField(max_length=100, null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='steps',
            name='body_en',
            field=models.TextField(max_length=100, null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='steps',
            name='body_ru',
            field=models.TextField(max_length=100, null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='steps',
            name='body_uz',
            field=models.TextField(max_length=100, null=True, verbose_name='body'),
        ),
    ]
