# Generated by Django 4.2.3 on 2023-07-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_about_faqs_our_keys_of_service_alter_card_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='team_images', verbose_name='image')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=30, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=30, null=True, verbose_name='name')),
                ('name_uz', models.CharField(max_length=30, null=True, verbose_name='name')),
                ('position', models.CharField(max_length=50, null=True, verbose_name='position')),
                ('position_en', models.CharField(max_length=50, null=True, verbose_name='position')),
                ('position_ru', models.CharField(max_length=50, null=True, verbose_name='position')),
                ('position_uz', models.CharField(max_length=50, null=True, verbose_name='position')),
                ('description', models.TextField(null=True, verbose_name='description')),
                ('description_en', models.TextField(null=True, verbose_name='description')),
                ('description_ru', models.TextField(null=True, verbose_name='description')),
                ('description_uz', models.TextField(null=True, verbose_name='description')),
            ],
        ),
        migrations.AlterField(
            model_name='callback',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='callback',
            name='subject',
            field=models.CharField(max_length=100, null=True, verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='name_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='team',
            name='position',
            field=models.CharField(max_length=50, null=True, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='team',
            name='position_en',
            field=models.CharField(max_length=50, null=True, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='team',
            name='position_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='team',
            name='position_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='team',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='team',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='team',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='team',
            name='title_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='team',
            name='work',
            field=models.CharField(max_length=70, null=True, verbose_name='work'),
        ),
        migrations.AlterField(
            model_name='team',
            name='work_en',
            field=models.CharField(max_length=70, null=True, verbose_name='work'),
        ),
        migrations.AlterField(
            model_name='team',
            name='work_ru',
            field=models.CharField(max_length=70, null=True, verbose_name='work'),
        ),
        migrations.AlterField(
            model_name='team',
            name='work_uz',
            field=models.CharField(max_length=70, null=True, verbose_name='work'),
        ),
    ]
