# Generated by Django 4.2.3 on 2023-07-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_testimonial_alter_callback_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addvertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='images', verbose_name='photo')),
                ('link', models.CharField(max_length=100, null=True, verbose_name='link')),
            ],
        ),
        migrations.AlterField(
            model_name='services',
            name='photo',
            field=models.ImageField(null=True, upload_to='images', verbose_name='photo'),
        ),
    ]
