# Generated by Django 4.2.3 on 2023-07-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_audit_assuranse_finansial_saving_strategic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='email')),
                ('message', models.TextField(null=True, verbose_name='message')),
            ],
        ),
    ]
